<a href="https://colab.research.google.com/github/ulises1229/INTRO-PYTHON-ENESJ/blob/master/code/d%C3%ADa2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Día 2 - Almacenamiento de datos
##### Autor: Ulises Olivares
##### uolivares@unam.mx
##### 01 septiembre de 2020

#### Diccionarios

In [1]:
# Uso de diccionarios

frutas= {'Fresa':'rojo', 'Limón':'verde', 'Kiwi': ['cafe', 'verde']}
for fruta, color in frutas.items():
  print(fruta + " es de color: " + str(color))



Fresa es de color: rojo
Limón es de color: verde
Kiwi es de color: ['cafe', 'verde']


Ejercicio 1 - Diccionarios

In [5]:
# Recuperar los precios de artículos para calcular el total de la compra
oficina = {'hojas':'32.5', 'tijeras':'50.45', 'lápiz':'10'}
claves = {'1': 'hojas', '2': 'tijeras', '3':'lápiz'}

producto = input("Selecciona un objeto de  la lista: \n 1) Hojas \n 2) Tijeras \n 3) Lápiz \n")
cant = int(input("¿Cuantos productos vas a comprar? \n"))

precio = float(oficina[claves[producto]])
             
print("El total a pagar es de: " + str(precio * cant))


Selecciona un objeto de  la lista: 
 1) Hojas 
 2) Tijeras 
 3) Lápiz 
1
¿Cuantos productos vas a comprar? 
3
El total a pagar es de: 97.5


In [7]:
# Variante sencilla del ejercicio anterior(usando un solo diccionario)
producto = input("Escribe un objeto de  la lista: \n hojas \n tijeras \n lápiz \n")
cant = int(input("¿Cuantos artículos vas a comprar?\n"))
precio = float(oficina[producto])
print("El total a pagar es de: " + str(precio * cant))

Escribe un objeto de  la lista: 
 hojas 
 tijeras 
 lápiz 
hojas
¿Cuantos artículos vas a comprar?
1
El total a pagar es de: 32.5


### Funciones

In [ ]:

def suma(num1, num2):
  """
    Realiza la sumatoria de dos números
    Input:
    Salidas: 
  """
  suma = num1 + num2
  return suma

def factorial(num):
  
  for i in range(1, num):
    
  return 


if __name__ == "__main__":
  print("Main")
  a = [1,2,3,4,5,6,7,8,9]
  b = [1,2,3,4,5,6,7,8,9]

  for i in range(0, len(a)):
    print("Suma del elemento: " + str(i) + " es: " + str(suma(a[i], b[i])))

  #print("suma Main: " + str(suma(a, b)))

Main
Suma del elemento: 0 es: 2
Suma del elemento: 1 es: 4
Suma del elemento: 2 es: 6
Suma del elemento: 3 es: 8
Suma del elemento: 4 es: 10
Suma del elemento: 5 es: 12
Suma del elemento: 6 es: 14
Suma del elemento: 7 es: 16
Suma del elemento: 8 es: 18


Ejercicio 2 - Funciones

In [28]:
# Calcular el factorial de un número
def factorial(n):
  fac = 1
  for i in range(1, n+1):
    fac *= i
  return fac

n = 10
print("Factorial de: " + str(n) + " = " + str(factorial(n)))


# Calcular si una cadena es palíndroma
def palindroma(cad):
  ban = True
  for i in range(len(cad)):
    if(cad[i] != cad[len(cad)-1-i]):
      ban = False
      break
  return ban 

cad = "oso"
if(palindroma(cad)):
  print(cad + " SI es palindroma")
else:
  print(cad + " NO es palindroma")


Factorial de: 10 = 3628800
oso si es palindroma


### Números aleatorios

Ejercicio 3 - Histograma

In [34]:
import random as rn

def generarNumeros(n):
  randomNum = []
  for i in range(n):
    randomNum.append(rn.randint(1, 99))
  return randomNum


def genHistograma(random, hist):
  for i in random:
    indice = int(i/len(hist))
    #print("indice: " + str(indice) + " num: " + str(i) )
    hist[indice] += 1
    #print("Elemento i: " + str (i) + " Pos: " + str(int(i/len(hist))))
  return hist

# Inicializar hostograma 10 posiciones
hist = [0,0,0,0,0,0,0,0,0,0]
n = 10000 #10K elementos

# inicializar 10,000 números aleatorios
random = generarNumeros(n)

# contabilizar elementos y generar histograma
hist = genHistograma(random, hist)

print("Histograma resultante: " + str(hist))

# Verificar resultado 
# La suma de los elementos de hist debe ser igual que n
if (sum(hist) == n):
  print("El resultado es correcto")
else:
  print("Existen elementos faltantes")

Histograma resultante: [885, 1044, 1014, 1011, 953, 1092, 983, 1003, 1022, 993]
El resultado es correcto


#### *Numpy*

Demostrar el uso de arreglos unidimensionales y bi-dimensionales utilizando numpy.


In [ ]:
# importar librería de numpy 
import numpy as np

# Creara un arreglo bi-dimensional
a = np.array([[1.0,2,3], 
              [4,5,6]], 
             dtype = np.float16)
# Imprimir matriz
print(a)

# IMP
print("Dimensiones: " + str(a.ndim))
print("Forma: " + str(a.shape))
print("Tipo de datos: " + str(a.dtype))

[[1. 2. 3.]
 [4. 5. 6.]]
Dimensiones: 2
Forma: (2, 3)
Tipo de datos: float16


In [ ]:
# Creación de arreglos
# Arreglo de 1s
ones = np.ones((3,5), dtype=np.float32)
# Arreglo de 0s
zeros = np.zeros((5,5), dtype=np.float32)

#Impresión de matrices
print(ones)
print(zeros)

print("Matriz 1s tiene: " + str(len(ones)) + " filas y " + str(len(ones[0])) + " columnas")

# Acceso a la matriz usando índices
filas = len(ones)
columnas = len(ones[0])

print("Impresión utilizando índices")
for i in range(filas):
  for j in range(columnas):
    print(ones[i][j], end= " ")
  print(" ")

print("Impresión utilizando elementos")
# Acceso usando elementos
for i in ones:
  for j in i:
    print(j , end =" ")
  print(" ")

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriz 1s tiene: 3 filas y 5 columnas
Impresión utilizando índices
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
Impresión utilizando elementos
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  
1.0 1.0 1.0 1.0 1.0  


#### Ejercicio 4 - Iterar sobre la diagonal principal

In [ ]:
# Ejercicio 4 1 en diagonal principal y traza de una matrix
zeros = np.zeros((10,10), dtype=np.float32)
print("Matriz Original: \n" + str(zeros))

for i in range(len(zeros)):
  zeros[i][i] = 1

# Calcular la traza de una matriz
traza = 0
for i in range(len(zeros)):
  traza =  traza + zeros[i][i] 

print("La traza de la matriz es: " + str(traza))

print("Matriz con 1's: \n" + str(zeros))

Matriz Original: 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
La traza de la matriz es: 10.0
Matriz con 1's: 
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### Ejercicio 5 - Escritura en elementos pares e impares

In [42]:
import numpy as np

# Generar un vector (lineal) 10 elementos 0 - 99
A = np.arange(100)

for i in range(len(A)): 
  # Elementos pares
  if (A[i] % 2 == 0):
    A[i] = -2
  else:
    A[i] = -1
print(A) 


[-2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1
 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1
 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1
 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1 -2 -1
 -2 -1 -2 -1]


In [ ]:
# Generación de un vector a través del uso de rangos
np.arange(1, 100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
# Concatenando arreglos o matrices
A = np.ones((5,3), dtype = np.float32)
B = np.zeros((5,4), dtype = np.float32)

# concatenar matrices
np.concatenate([A,B], axis = 1)

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
# Uso de Astype para hacer un cast de tipos de datos
A = np.zeros((5,4), dtype = np.float32)
print(len(A[0]))

for i in range(len(A)):
  for j in range(len(A[0])):
    A[i][j] = np.pi
print(A)

print(A.astype(np.int16))

4
[[3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [ ]:
# Uso de np.zeros_like y np.ones_like
A = np.ones((4,4))
print(A)
# zeros_like genera un arreglo de las 
# mismas dimensiones que el original 
B = np.zeros_like(A)
print(B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Generación de arreglos aleatorios
A = np.random.random((5, 5))
print(A)
# Generación de números enteros del 0 al n-1 
n = 10
B= np.random.randint(10, size = (7,7))
print(B)

[[0.77660053 0.26296099 0.88039588 0.04823786 0.10309384]
 [0.48729586 0.3771756  0.48484433 0.34679897 0.74569246]
 [0.1103608  0.55375063 0.80777421 0.16883789 0.18751702]
 [0.41290608 0.6659239  0.41775295 0.94601225 0.19686526]
 [0.58423953 0.88600177 0.25069284 0.24865989 0.07879548]]
[[7 1 7 4 4 0 1]
 [4 6 8 7 4 1 0]
 [5 0 4 3 4 1 1]
 [6 2 2 0 7 6 7]
 [5 5 8 4 0 3 3]
 [7 0 3 2 7 4 2]
 [1 6 9 0 8 1 7]]


#### Ejercicio 6 - Lectura de un conjunto de elementos de una matriz

In [62]:
import random as rn

# Generar una matriz aleatorio de 10 x 10
A = np.random.randint(100, size=(10, 10))
print("Matriz original: \n" + str(A))

suma = 0
# Iterar sobre las filas
for i in range(len(A)):
  # Iterar sobre las columnas
  for j in range(i, len(A[0])):
    suma += A[i][j]

print("La sumatorio de los elementos del tríangulo superior es: " + str(suma))


Matriz original: 
[[74 73 62 44  0 88 98 64 49 29]
 [ 9 69  0 42 18 62 40 48 17 67]
 [15  5 40 58 84 63 30  0 56 66]
 [23 52 66 57 76 98 82 98  2 81]
 [20  3 76 15 94 96 81 41 31 27]
 [14 11 15 83  5 28 65 91 16  3]
 [53 82 60 35 32 40 88 58 49 74]
 [ 2 22 27  6  3 61 73 54  7 28]
 [99 74  5 96 24 70 86 49  6 96]
 [68 27 82 64 26 64 43 70 67  4]]
La sumatorio de los elementos del tríangulo superior es: 2872


In [ ]:
# Transformaciones de arreglos
A = np.array([1,2,3,4,5,6])
print(A)

# Transformar a 3 filas, 2 columnas
A = A.reshape(3, 2)
print(A)

# Se utiliza -1 para determinar cols
A = A.reshape(2, -1)
print(A)

# Transormar a un arreglo lineal
A = A.ravel()
print(A)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# Transpuesta de una matriz
A = np.arange(25).reshape(5,5)
print("Matriz Original: \n" + str(A))
# Imprimir matriz transpuesta
print("Matriz Transpuesta: \n" + str(A.T))
# Imprimir matriz 
print("Matriz Transpuesta: \n" + str(A.transpose((1,0))))



Matriz Original: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Matriz Transpuesta: 
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]
Matriz Transpuesta: 
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [ ]:
# Operadores Matemáticos
A = np.arange(100).reshape(10,10)
print("Primer Matriz: \n" + str(A))

B = np.arange(100, 200).reshape(10, 10)
print("Segunda Matriz: \n" + str(B))

# Calcular la suma de ambas matrices
print("Suma: "  + str(A + B))

# Calcular la resta de ambas matrices
print("Suma: "  + str(B - A))

# Calcular la multiplicación de ambas matrices
print("Suma: "  + str(A * B))

Primer Matriz: 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Segunda Matriz: 
[[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]]
Suma: [[100 102 104 106 108 110 112 114 116 118]
 [120 122 124 126 128 130 132 134 136 138]
 [140 142 144 146 148 150 152 154 156 158]
 [160 162 164 166 168 170 172 174 176 178]
 [180 182 184 186 188 190 1

In [ ]:
# Operadores lógicos

A = np.random.random((5,5))
print("Matriz Original: \n" + str(A))

# Operador lógico
print("Operador lógico a >5 \n" + str(a>0.5))

Matriz Original: 
[[0.0124458  0.75318949 0.51012785 0.14677449 0.38131653]
 [0.63214844 0.49240062 0.72302018 0.5913991  0.34027848]
 [0.52156944 0.39808869 0.46779844 0.03746587 0.8252981 ]
 [0.8354298  0.7554512  0.53322169 0.09566736 0.7134824 ]
 [0.6791975  0.23094997 0.0116702  0.10245596 0.39682071]]
Operador lógico a >5 
[[False  True False  True  True  True  True  True False  True]
 [ True False  True False False  True  True  True  True False]
 [ True  True  True False  True  True  True False False  True]
 [ True False  True  True False False  True False False False]
 [False  True False  True False  True  True False  True  True]
 [ True False  True False False False  True False False  True]
 [ True False  True  True False False False False False False]
 [False False  True  True False  True False  True  True False]
 [ True False  True False False  True False  True False False]
 [False False False False  True  True  True False  True False]]


In [ ]:
# Operaciones in-situ 
A = np.random.randint(10, size= (5,5))
print("Matriz A Original: \n" + str(A))

B = A = np.random.randint(10, size= (5,5))
print("Matriz B Original: \n" + str(B))

# Operación in-situ
A += B
print("Matriz A Modificada: \n" + str(A))

Matriz A Original: 
[[0 0 7 9 2]
 [3 6 9 3 0]
 [1 1 2 5 1]
 [3 5 6 9 4]
 [1 1 7 7 5]]
Matriz B Original: 
[[2 8 3 7 1]
 [3 1 1 7 0]
 [7 5 0 5 1]
 [2 9 5 9 5]
 [3 4 6 8 0]]
Matriz A Modificada: 
[[ 4 16  6 14  2]
 [ 6  2  2 14  0]
 [14 10  0 10  2]
 [ 4 18 10 18 10]
 [ 6  8 12 16  0]]


In [ ]:
# Funciones universales
A = np.random.randint(10, size= (5,5))
print("Matriz A Original: \n" + str(A))

# Calcular Raiz cuadrada
print("Raiz Cuadrada: \n" + str(np.sqrt(A)))


Matriz A Original: 
[[0 7 0 0 0]
 [8 7 2 1 4]
 [3 7 6 9 9]
 [3 9 2 3 4]
 [3 7 2 3 5]]
Raiz Cuadrada: 
[[0.         2.64575131 0.         0.         0.        ]
 [2.82842712 2.64575131 1.41421356 1.         2.        ]
 [1.73205081 2.64575131 2.44948974 3.         3.        ]
 [1.73205081 3.         1.41421356 1.73205081 2.        ]
 [1.73205081 2.64575131 1.41421356 1.73205081 2.23606798]]


#### Inversa de una matriz


In [ ]:
# Inversa de una matriz
import numpy as np

# Inicializar una matriz 
A = np.random.randint(10, size= (5,5))
print("Matriz A Original: \n" + str(A))

# Calcular matriz inversa
B = np.linalg.inv(A)
print("Matriz Inversa A^-1: \n" + str(B))

Matriz A Original: 
[[8 0 1 9 5]
 [9 2 4 5 2]
 [8 5 1 1 3]
 [5 7 9 2 9]
 [1 7 3 7 1]]
Matriz Inversa A^-1: 
[[-0.0137931   0.08390805  0.06781609 -0.02873563 -0.04367816]
 [-0.04396552 -0.06587644  0.11199713 -0.00826149  0.08994253]
 [-0.09094828  0.17826868 -0.14658764  0.06052443 -0.00675287]
 [ 0.06810345  0.00237069 -0.06400862 -0.02478448  0.06982759]
 [ 0.11767241 -0.17417385  0.0360273   0.0784842  -0.05445402]]


#### Ejercicio 7 - Operadores aritméticos

In [66]:
import numpy as np

# Generar una matriz de 10 x 10
A = np.random.randint(10, size = (10,10))
print("Matriz A Original: \n" + str(A))

# Calcular el cuadraro de una matriz de 10 x 10
print("Cuadrado de la matriz: \n" + str(np.square(A)))

# Multiplicación de matrices
print("Inversa de de la matriz: \n" + str(np.linalg.inv(A)))



Matriz A Original: 
[[6 6 5 8 9 2 6 7 8 5]
 [8 7 4 4 2 7 6 3 7 2]
 [8 2 0 5 5 5 9 2 1 0]
 [4 9 6 5 3 1 2 5 4 9]
 [1 8 2 3 2 6 9 7 5 5]
 [1 3 1 7 4 1 9 4 1 1]
 [7 0 3 0 6 5 3 3 0 1]
 [6 8 8 8 6 9 2 5 8 2]
 [1 1 1 5 7 3 1 8 6 2]
 [9 1 1 0 2 5 3 5 1 7]]
Cuadrado de la matriz: 
[[36 36 25 64 81  4 36 49 64 25]
 [64 49 16 16  4 49 36  9 49  4]
 [64  4  0 25 25 25 81  4  1  0]
 [16 81 36 25  9  1  4 25 16 81]
 [ 1 64  4  9  4 36 81 49 25 25]
 [ 1  9  1 49 16  1 81 16  1  1]
 [49  0  9  0 36 25  9  9  0  1]
 [36 64 64 64 36 81  4 25 64  4]
 [ 1  1  1 25 49  9  1 64 36  4]
 [81  1  1  0  4 25  9 25  1 49]]
Inversa de de la matriz: 
[[-0.19961654  0.29983938 -0.00432645  0.17652517 -0.17711762  0.08272503
   0.10785618 -0.17784635  0.18232593 -0.07203926]
 [-0.32868895  0.2324998   0.1930608   0.37381551 -0.04556008 -0.09409127
   0.13827851 -0.21677544  0.27893069 -0.30379883]
 [ 0.10570453  0.04488377 -0.33588277 -0.13791622 -0.04585367  0.24037212
   0.12015461  0.08655869 -0.17873794  0.096