<a href="https://colab.research.google.com/github/ulises1229/INTRO-PYTHON-ENESJ/blob/master/code/d%C3%ADa5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Día5 - Deep Learning con Pythorch**
+ Autor: Ulises Olivares, Walter André Reyes
+ uolivares@unam.mx
+ 04 de septiembre de 2020

---
Contenido basado en la documentación oficial de Pythorch: 
- https://pytorch.org/tutorials/

---



---
# Parte I - ¿Qué es Pythorch?
---
Es un paquete informático científico basado en Python dirigido a dos conjuntos de
audiencias:

- Un reemplazo de NumPy para usar el poder de cómputo de los GPU.

- Una plataforma de investigación de (deep learning) que proporciona máxima flexibilidad y velocidad

**Tensores**
---------------

+ Los tensores son similares a los ndarrays de NumPy, con la adición de que también se pueden usar en un GPU para acelerar los cálculos.



In [ ]:
# Google Colab soporta Pythorch por default
import torch


**Nota**


Se declara una matriz no inicializada, esta matriz no contiene valores definidos antes de su uso. Cuando se crea una matriz no inicializada, los valores que estaban en la memoria asignada en ese momento aparecerán como valores iniciales.



In [ ]:
# Matriz no inicializada de 5 filas y 3 columnas
x = torch.empty(5, 3)
print(x)

tensor([[1.7501e-35, 0.0000e+00, 3.9236e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.7970e-35, 0.0000e+00, 1.7966e-35],
        [0.0000e+00, 1.7969e-35, 0.0000e+00],
        [5.6052e-45, 0.0000e+00, 0.0000e+00]])


*Construir* una matriz no inicializada de 5x3:



In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[1.7502e-35, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [2.1762e-04, 1.7063e-07, 1.3090e+22],
        [2.6657e-09, 8.4576e+20, 4.1545e+21],
        [2.6952e-09, 1.6987e+22, 0.0000e+00]])


Construir una matriz inicializada de forma aleatoria:



In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5340, 0.7008, 0.2449],
        [0.9203, 0.7850, 0.1195],
        [0.2695, 0.4620, 0.8420],
        [0.8809, 0.6356, 0.8460],
        [0.6782, 0.9257, 0.7881]])


Construir una matriz de zeros y de tyopo long:

- Ver tipos de datos de pythorch en el siguiente [LINK](https://pytorch.org/docs/stable/tensor_attributes.html)


In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


**Construir un Tensor a partir de datos:**
  + Se especifican los elementos entre corchetes. E.g. [1,2,3,5]




In [ ]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


**Crear un tensor basado en un tensor existente**

Este método reutilizá las propiedades del tensor de entrada. E.g. **dtype**, a menos que los nuevos valores se especifiquen por el usuario.

In [ ]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # sobreescibir dtype!
print(x)                                      # el resultado tiene el mismo tamaño.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.0110,  0.1915, -1.2654],
        [ 0.4731, -1.5652, -1.3700],
        [-0.1778, -0.7414,  1.1132],
        [-0.9819, -0.5176,  1.3193],
        [ 0.0545,  1.6242, -0.3171]])


**Obtener el tamaño de un tensor:**



In [ ]:
print(x.size())

torch.Size([5, 3])


<h4>Nota</h4><p>

`torch.Size`

Es de hecho una tupla, entonces soporta las operaciones de tuplas.</p></div>

**Operaciones**

Existen múltiples formas de especificar (denotar) operaciones en pythorch. En el siguiente ejemplo, se utilizara la operación de adición. 

**Suma: sintaxis 1**



In [ ]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.3237,  0.9526, -0.7096],
        [ 1.1974, -0.9444, -0.4352],
        [ 0.3315, -0.4599,  1.5977],
        [-0.5694,  0.0638,  1.8248],
        [ 0.2995,  2.3940,  0.5591]])


**Suma: sintaxis 2**



In [ ]:
print(torch.add(x, y))

tensor([[ 1.3237,  0.9526, -0.7096],
        [ 1.1974, -0.9444, -0.4352],
        [ 0.3315, -0.4599,  1.5977],
        [-0.5694,  0.0638,  1.8248],
        [ 0.2995,  2.3940,  0.5591]])


**Suma: Sintaxis 3** 
- pasar la variable resultado como un argumento.

In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.3237,  0.9526, -0.7096],
        [ 1.1974, -0.9444, -0.4352],
        [ 0.3315, -0.4599,  1.5977],
        [-0.5694,  0.0638,  1.8248],
        [ 0.2995,  2.3940,  0.5591]])


**Suma: Sintaxis 4**
- Operación in-situ


In [ ]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3237,  0.9526, -0.7096],
        [ 1.1974, -0.9444, -0.4352],
        [ 0.3315, -0.4599,  1.5977],
        [-0.5694,  0.0638,  1.8248],
        [ 0.2995,  2.3940,  0.5591]])


**Nota**

Cualquier operación que modifique un tensor in-situ lleva el sufijo `_` 

Por ejemplo: 

``x.copy_(y)``, ``x.t_()``, modificarán al tensor ``x``

- **¡Es posible utilizar la notación de indexación similar a Numpy!**

In [ ]:
print(x[:, 1])

tensor([ 0.1915, -1.5652, -0.7414, -0.5176,  1.6242])


**Modificar el tamaño:** Si es necesario modificar el tamaño o la forma de un tensoer, se puede utilizar:

``torch.view``:



In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # el tamaño -1 se asigna automáticamente (infiere) de la otra dimensión.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Si se tiene un único elemento en el tensor, se puede emplear ``.item()`` para obtener el valor como un número de Python.

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5930])
0.593023955821991


**Revisar más tarde:**

  - Más de 100 operaciones con tensores incluidos:
    + Transposiciones
    + Indexación
    + Subconjuntos
    + Operaciones matemáticas
    + Operaciones de álgebra lineal
    + Números aleatorios, etc

Todas estas operaciones están descritas
  `aquí <https://pytorch.org/docs/torch>`_.

Conversión de Torch Tensor a Numpy Array y viceversa
---

La conversión es muy sencilla

El arraglo de Numpy y el Tensor compartirán la ubicación de memoria subyacente
(si el tensor de Torch está en el CPU), cambiar un elemento modificará atomáticamente el otro.

**Convirtiendo un Tensor Torch a un Numpy Array**

In [ ]:
# Torch tensor
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# Arreglo de numpy
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]



Verificar el arraglo de numpy.


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Convirtiendo el arreglo de Numpy a un Tensor Torch
---
Verificar como el arraglod e Numpy modifica automáticamente al tensor Torch.

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Todos ls tensores que se definen en CPU (con excepción de CharTensor) pueden convertirse a un arreglo de Numpy y viceversa.

Tensores de CUDA -> (GPU)
------------
Los tensores pueden ser movido a un GPU (device) utilizando el método ``.to``.

Sólo podrán ejecutar este código si cuentan con un GPU de NVIDIA y el framework  de CUDA instalado. De lo contrario pueden utilizar Google Colab ``<https://colab.research.google.com/>`` o  Kaggle `<https://www.kaggle.com/>``



In [ ]:
# se verificará si CUDA está disponible
# Se usarán objetos ``torch.device`` para mover objetos al device y viceversa
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")        # Objeto de CUDA device
    x = torch.ones(3000,3000)                  # Definición de una matriz de 2x3 de 1s
    y = torch.ones_like(x, device=device)  # Crear un tensor directamente en GPU(device)
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x * y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` permite modificar el tipo de datos!
else:
    print("CUDA no esta disponible :'(")

CUDA no esta disponible :'(
